# Generated by CoffeeScript 1.6.3
(->
  app = module.exports = require("appjs")
  app.serveFilesFrom __dirname + "/content"
  
  menubar = app.createMenu([
    label: "&File"
    submenu: [
      label: "E&xit"
      action: ->
        window.close()
    ]
  ,
    label: "&Window"
    submenu: [
      label: "Fullscreen"
      action: (item) ->
        window.frame.fullscreen()
        console.log item.label + " called."
    ,
      label: "Minimize"
      action: ->
        window.frame.minimize()
    ,
      label: "Maximize"
      action: ->
        window.frame.maximize()
    ,
      label: ""
    ,
      label: "Restore"
      action: ->
        window.frame.restore()
    ]
  ])
  menubar.on "select", (item) ->
    console.log "menu item " + item.label + " clicked"

  trayMenu = app.createMenu([
    label: "Show"
    action: ->
      window.frame.show()
  ,
    label: "Minimize"
    action: ->
      window.frame.hide()
  ,
    label: "Exit"
    action: ->
      window.close()
  ])
  statusIcon = app.createStatusIcon(
    icon: "./data/content/icons/32.png"
    tooltip: "AppJS Hello World"
    menu: trayMenu
  )
  window = app.createWindow(
    width: 640
    height: 800
    showChrome: true
    icons: __dirname + "/content/icons"
  )

  window.on "create", ->
    console.log "Window Created"
    window.frame.show()
    window.frame.center()
    window.frame.setMenuBar menubar

  window.on "ready", ->
    Command_Option_J = undefined
    F12 = (e) ->
      e.keyIdentifier is "F12"

    Command_Option_J = (e) ->
      e.keyCode is 74 and e.metaKey and e.altKey

    console.log "Window Ready"
    window.process = process
    window.module = module

    window.app =
      shell: require("shelljs")
      keyboard: require("keyboard")
      fs: require("fs")
      mime: require("mime")

    window.addEventListener "keydown", (e) ->
      window.frame.openDevTools()  if F12(e) or Command_Option_J(e)
    # window.frame.openDevTools()
    
  window.on "close", ->
    console.log "Window Closed"

).call this
